import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const models = [
  // IMAGE: Text-to-Image
  {
    id: "flux-2/pro-text-to-image",
    label: "Flux 2 Pro",
    labelTh: "Flux 2 Pro",
    type: "text-to-image",
    apiType: "market",
    requiresImage: false,
    creditCost: 5,
    category: "image",
  },
  {
    id: "gpt-image/1.5-text-to-image",
    label: "GPT Image 1.5",
    labelTh: "GPT Image 1.5",
    type: "text-to-image",
    apiType: "gpt4o",
    requiresImage: false,
    creditCost: 8,
    category: "image",
  },
  {
    id: "ideogram/v3-text-to-image",
    label: "Ideogram V3",
    labelTh: "Ideogram V3",
    type: "text-to-image",
    apiType: "market",
    requiresImage: false,
    creditCost: 5,
    category: "image",
  },
  {
    id: "google/imagen4",
    label: "Google Imagen 4",
    labelTh: "Google Imagen 4",
    type: "text-to-image",
    apiType: "market",
    requiresImage: false,
    creditCost: 5,
    category: "image",
  },
  {
    id: "grok-imagine/text-to-image",
    label: "Grok Imagine",
    labelTh: "Grok Imagine",
    type: "text-to-image",
    apiType: "market",
    requiresImage: false,
    creditCost: 5,
    category: "image",
  },
  // IMAGE: Image-to-Image
  {
    id: "flux-2/pro-image-to-image",
    label: "Flux 2 Pro (i2i)",
    labelTh: "Flux 2 Pro (แก้ไขรูป)",
    type: "image-to-image",
    apiType: "market",
    requiresImage: true,
    creditCost: 6,
    category: "image",
  },
  // IMAGE: Utilities
  {
    id: "recraft/remove-background",
    label: "Remove BG",
    labelTh: "ลบพื้นหลัง",
    type: "remove-background",
    apiType: "market",
    requiresImage: true,
    creditCost: 3,
    category: "image",
  },
  {
    id: "topaz/image-upscale",
    label: "Upscale",
    labelTh: "ขยายรูป",
    type: "upscale",
    apiType: "market",
    requiresImage: true,
    creditCost: 4,
    category: "image",
  },
  // VIDEO: Text-to-Video
  {
    id: "kling-2.6/text-to-video",
    label: "Kling 2.6",
    labelTh: "Kling 2.6 (วิดีโอ)",
    type: "text-to-video",
    apiType: "market",
    requiresImage: false,
    creditCost: 20,
    category: "video",
  },
  {
    id: "wan/2-6-text-to-video",
    label: "Wan 2.6",
    labelTh: "Wan 2.6 (วิดีโอ)",
    type: "text-to-video",
    apiType: "market",
    requiresImage: false,
    creditCost: 15,
    category: "video",
  },
  {
    id: "grok-imagine/text-to-video",
    label: "Grok Video",
    labelTh: "Grok (วิดีโอ)",
    type: "text-to-video",
    apiType: "market",
    requiresImage: false,
    creditCost: 18,
    category: "video",
  },
  // VIDEO: Image-to-Video
  {
    id: "kling-2.6/image-to-video",
    label: "Kling 2.6 (i2v)",
    labelTh: "Kling 2.6 (รูปเป็นวิดีโอ)",
    type: "image-to-video",
    apiType: "market",
    requiresImage: true,
    creditCost: 22,
    category: "video",
  },
  {
    id: "wan/2-6-image-to-video",
    label: "Wan 2.6 (i2v)",
    labelTh: "Wan 2.6 (รูปเป็นวิดีโอ)",
    type: "image-to-video",
    apiType: "market",
    requiresImage: true,
    creditCost: 18,
    category: "video",
  },
  // AUDIO: Text-to-Speech
  {
    id: "elevenlabs/text-to-speech-turbo-2-5",
    label: "ElevenLabs TTS",
    labelTh: "สร้างเสียงพูด",
    type: "text-to-audio",
    apiType: "market",
    requiresImage: false,
    creditCost: 5,
    category: "audio",
  },
  {
    id: "elevenlabs/sound-effect-v2",
    label: "Sound Effect",
    labelTh: "สร้างเสียงเอฟเฟกต์",
    type: "text-to-audio",
    apiType: "market",
    requiresImage: false,
    creditCost: 4,
    category: "audio",
  },
  // MUSIC
  {
    id: "suno/v4.5",
    label: "Suno V4.5",
    labelTh: "สร้างเพลง (Suno)",
    type: "text-to-music",
    apiType: "suno",
    requiresImage: false,
    creditCost: 10,
    category: "music",
  },
];

export async function GET() {
  return NextResponse.json({ models });
}
